

sensor:
  - name: "Status do S23 Ultra do Edu"
    unique_id: status_do_s23_ultra_do_edu
    state: "{{ states('sensor.nivel_da_bateria_do_s23_ultra_do_edu') }}"
    icon: "{{ state_attr('sensor.nivel_da_bateria_do_s23_ultra_do_edu', 'icon') }}"
    device_class: battery
    unit_of_measurement: "%"
    attributes:
      status: >-
        {% if is_state('sensor.status_da_bateria_do_s23_ultra_do_edu', 'discharging') -%}
          Em Uso
        {% elif is_state('sensor.status_da_bateria_do_s23_ultra_do_edu', 'charging') -%}
          Carregando
          {%- if is_state('sensor.tipo_de_carregamento_do_s23_ultra_do_edu', 'ac') -%}
            {{ " - Tomada" }}
          {% elif is_state('sensor.tipo_de_carregamento_do_s23_ultra_do_edu', 'usb') -%}
            {{ " - USB" }}
          {% elif is_state('sensor.tipo_de_carregamento_do_s23_ultra_do_edu', 'wireless') -%}
            {{ " - Wireless" }}
          {% elif is_state('sensor.tipo_de_carregamento_do_s23_ultra_do_edu', 'dock') -%}
            {{ " - Dock" }}
          {% endif %}
        {% elif is_state('sensor.status_da_bateria_do_s23_ultra_do_edu', 'full') -%}
          Carga Completa
        {% elif is_state('sensor.status_da_bateria_do_s23_ultra_do_edu', 'not_charging') -%}
          Not Charging
        {% endif %}
        
  - name: "Status do DVR da Casa"
    unique_id: status_do_dvr_da_casa
    icon: mdi:cctv
    state: >-
      {% from 'format_date.jinja' import format_date %}
      Uso da CPU: {{ states('sensor.uso_do_processador_do_dvr_da_casa') }}% · 
      {{- " Último Boot: " + format_date(states('sensor.ultima_inicializacao_do_dvr_da_casa')) }}







