triggers:
      - trigger: state
        entity_id: select.selecao_atual_do_card_tv_do_edu

select:
  - name: "Seleção Atual do Card TV do Edu"
    unique_id: "selecao_atual_do_card_tv_do_edu"
    icon: mdi:palette-swatch-variant
    optimistic: true
    options: "{{ ['Volume', 'Fonte'] }}"
    state: "{{ 'Fonte' if trigger.to_state.state == 'unknown' else trigger.to_state.state }}"
    select_option:
      - action: select.select_option
        data:
          option: "{{ option }}"
        target:
          entity_id: select.selecao_atual_do_card_tv_do_edu
